// packages/react/src/WebMcpContext.tsx
import { createContext } from 'react';
import type {
  PolicyContext,
  WebMcpRegistry,
} from '@tooluminati/core';
import type { WebMcpPolicySet } from '@tooluminati/policies';

export interface WebMcpReactContextValue {
  registry: WebMcpRegistry;
  enabled: boolean;
  policies?: WebMcpPolicySet;
  policyContext?: PolicyContext | undefined;
  namespace?: string | undefined;
}

export const WebMcpContext = createContext<WebMcpReactContextValue | null>(
  null,
);

// packages/angular/src/web-mcp-context.ts
import { InjectionToken } from '@angular/core';
import type {
  PolicyContext,
  WebMcpRegistry,
} from '@tooluminati/core';
import type { WebMcpPolicySet } from '@tooluminati/policies';

export interface WebMcpAngularContextValue {
  registry: WebMcpRegistry;
  enabled: boolean;
  policies?: WebMcpPolicySet;
  policyContext?: PolicyContext | undefined;
  namespace?: string | undefined;
}

export const WEB_MCP_CONTEXT = new InjectionToken<WebMcpAngularContextValue>(
  'WEB_MCP_CONTEXT',
);
