// packages/angular/src/web-mcp-scope.component.ts
import {
  Component,
  DestroyRef,
  effect,
  inject,
  input,
} from '@angular/core';
import type {
  WebMcpToolDescriptor,
  WebMcpToolSource,
} from '@tooluminati/core';
import { injectWebMcpRegistry } from './inject-web-mcp-registry';

@Component({
  selector: 'web-mcp-scope',
  standalone: true,
  template: '<ng-content />',
})
export class WebMcpScopeComponent {
  readonly tools = input.required<WebMcpToolDescriptor[]>();
  readonly source = input<WebMcpToolSource>('scope');
  readonly namespaceSegment = input<string | undefined>(undefined);

  constructor() {
    const registry = injectWebMcpRegistry();
    const destroyRef = inject(DestroyRef);

    effect((onCleanup) => {
      const segment = this.namespaceSegment();
      const scopedTools = segment
        ? this.tools().map((tool) => ({
            ...tool,
            name: `${segment}.${tool.name}`,
          }))
        : this.tools();

      const registrations = scopedTools.map((tool) =>
        registry.registerTool(tool, {
          source: this.source(),
        }),
      );

      onCleanup(() => {
        for (const registration of registrations) {
          registration.abort();
        }
      });
    });

    destroyRef.onDestroy(() => undefined);
  }
}

// packages/react/src/WebMcpScope.tsx
import { useMemo, type ReactNode } from 'react';
import type {
  WebMcpToolDescriptor,
  WebMcpToolSource,
} from '@tooluminati/core';
import { useWebMcpContextValue } from './useWebMcpRegistry';
import { useWebMcpTools } from './useWebMcpTools';

export interface WebMcpScopeProps {
  children: ReactNode;
  tools: WebMcpToolDescriptor[];
  source?: WebMcpToolSource;
  namespaceSegment?: string | undefined;
}

export function WebMcpScope({
  children,
  tools,
  source = 'scope',
  namespaceSegment,
}: WebMcpScopeProps) {
  const { namespace } = useWebMcpContextValue();
  const scopedTools = useMemo(
    () =>
      namespaceSegment
        ? tools.map((tool) => ({
            ...tool,
            name: `${namespaceSegment}.${tool.name}`,
          }))
        : tools,
    [namespaceSegment, tools],
  );

  void namespace;

  useWebMcpTools(scopedTools, [scopedTools], { source });

  return <>{children}</>;
}
